### ISSUE TITLE
bubble statistic isssues

### ISSUE THREAD

**Issue by xiaomiyongyuan** [fawaz-dabbaghieh/bubble_gun#4]
Hi!
It's a good tool,but i am puzzled about this:
I added a path on the example data, but in the end, only two bubbles inside the red box were counted. Why is that?
Below is my command:
`BubbleGun -g /home/jmhan/pangenome/SD/bubble/bubble_gun/example/paper_example2.gfa  bchains --bubble_json x.json`
![Snipaste_2024-03-27_21-54-01](https://github.com/fawaz-dabbaghieh/bubble_gun/assets/98016418/94c9d129-7787-4e46-8db8-cf945ec3e699)

**Comment by fawaz-dabbaghieh** [comment]
Hi!

Yes, the big bubble won't be counted because of the tip (node 312), this will break the algorithm, as a bubble or a superbubble is supposed to have one source and one sink node (nodes 89 and 25), but because of node 312, the algorithm will abort and won't report that structure

**Comment by xiaomiyongyuan** [comment]
Thank you very much for your reply,
i am not familiar with this field. Do you have any other software recommendations?
Thanks!
Junmin
