### ISSUE TITLE
Superbubbles with 2 entrances and 2 exits

### ISSUE THREAD

**Issue by kokyriakidis** [fawaz-dabbaghieh/bubble_gun#6]
Hi @fawaz-dabbaghieh 

Does this algorithm work for superbubbles with 2 entrances and 2 exits?

**Comment by fawaz-dabbaghieh** [comment]
@kokyriakidis No, as this would not follow the definition of a superbubble, as superbubble is defined as an acyclic subgraph with one source and one wink
